<?php

$cars = [
    [
        'id' => 1,
        'casa_automobilistica' => 'Ford',
        'modello' => 'Ford EcoSport',
        'prezzo' => 19249,
        'chilometraggio' => 9530,
        'prima_immatricolazione' => '2020 - 01 - 01',
        'CV' => 125,
        'carburante' => 'benzina',
        'classe_del_veicolo' => 'SUV',
        'numero_portiere' => 5,
        'cilindrata' => 998,
        'paese_origine' => 'italia',
        'targa' => 'GA071DJ',
        'numero_proprietari_precedenti' => 1,
        'specifiche_in_evidenza' => 'Cerchi in lega da 17, Controllo elettronico della corsia',
        'confort' => 'Alzacristalli elettrici, Bracciolo, Chiusura centralizzata,
        Sedile posteriore sdoppiato,
        Volante in pelle,
        Volante multifunzione,
        Controllo automatico clima,
        Sensori di parcheggio posteriori,
        Cruise ontrol',
        'sistema_multimediale' => 'Autoradio, boardcomputer
        bluetooth, vivavoce',
        'sicurezza' => 'Airbag, Airbag passeggero, Airbag Laterali, Immobilizzatore elettronico, ESP, ABS, Isofix',
        'immagine' => 'https://img-eu-c1.autohero.com/img/1df23062073c965808a6bec744746abb0753ebb125e9b15ab2efdea66ed34804/exterior/1/1116x744-31bedb40163d4d67bdbb1affc0652ae0.jpg'
    ],
    [
        'id' => 2,
        'casa_automobilistica' => 'Subaru',
        'modello' => 'Subaru XV',
        'prezzo' => 11.399,
        'chilometraggio' => 98860,
        'prima_immatricolazione' => '2013 - 01 - 01',
        'CV' => 150,
        'carburante' => 'GPL',
        'classe_del_veicolo' => 'SUV',
        'numero_portiere' => 5,
        'cilindrata' => 1995,
        'paese_origine' => 'italia',
        'targa' => 'EP219CB',
        'numero_proprietari_precedenti' => 2,
        'specifiche_in_evidenza' => 'Telecamera per parcheggio assistito, Trazione integrale, Fari Xenon, Cerchi in lega da 17',
        'confort' => 'Chiusura centralizzata, Alzacristalli elettrici
        Volante multifunzione, Cruise control, Controllo automatico clima, Leve al volante, Sedili riscaldati, Vetri oscurati',
        'sistema_multimediale' => 'Autoradio, Boardcomputer',
        'sicurezza' => 'Airbag paseggero, Airbag laterali, Airbag, ABS, ESP, Immobilizzatore elettronico, Controllo trazione, Isofix',
        'immagine' => 'https://img-eu-c1.autohero.com/img/381a99477afda94e93db5776e37fe5064deff7c34d704b5177e3afbe112e43e0/exterior/1/1116x744-bc6488bd272d4d6fa4ee5592f1ff6480.jpg'
    ],
    [
        'id' => 3,
        'casa_automobilistica' => 'Fiat',
        'modello' => 'Fiat Panda',
        'prezzo' => 14899,
        'chilometraggio' => 12240,
        'prima_immatricolazione' => '2020 - 07 - 01',
        'CV' => 70,
        'carburante' => 'ibrida',
        'classe_del_veicolo' => 'berlina',
        'numero_portiere' => 5,
        'cilindrata' => 999,
        'paese_origine' => 'italia',
        'targa' => 'GA853LP',
        'numero_proprietari_precedenti' => 1,
        'specifiche_in_evidenza' => 'Cerchi in lega da 15',
        'confort' => 'Alzacristalli elettrici, Bracciolo, Chiusura centralizzata, Climatizzatore, Sedile posteriore sdoppiato,Sensori di parcheggio posteriori, Volante multifunzione',
        'sistema_multimediale' => 'Autoradio, Bluetooth, Boardcomputer, Vivavoce',
        'sicurezza' => 'ABS, Airbag, Airbag laterali, Airbag Passeggero, Airbag testa, Controllo trazione, ESP, Immobilizzatore elettronico, Isofix',
        'immagine' => 'https://img-eu-c1.autohero.com/img/bee89484c37400749047cb789ffbe00e9debf6ed3c2a8db42b8b256af80d14dc/exterior/1/1116x744-438fa14b981f4e25a28f7223c1fb397c.jpg'
    ],
    [
        'id' => 4,
        'casa_automobilistica' => 'Alfa Romeo',
        'modello' => 'Alfa Romeo Giulia',
        'prezzo' => 34999,
        'chilometraggio' => 29885,
        'prima_immatricolazione' => '2020 - 03 - 01',
        'CV' => 210,
        'carburante' => 'diesel',
        'classe_del_veicolo' => 'berlina',
        'numero_portiere' => 5,
        'cilindrata' => 2143,
        'paese_origine' => 'italia',
        'targa' => 'FY765CJ',
        'numero_proprietari_precedenti' => 1,
        'specifiche_in_evidenza' => 'Controllo elettronico della corsia, Sistema di navigazione, Trazione integrale, Cerchi in lega da 18, Fari Xenon',
        'confort' => 'Alzacristalli elettrici, Bracciolo, Chiusura centralizzata, Controllo automatico clima, Interni in pelle, Sedile posteriore sdoppiato, Sensori di parcheggio anteriori, Sensori di parcheggio posteriori, Volante multifunzione, Adaptive cruise control, Volante in pelle',
        'sistema_multimediale' => 'Bluetooth, Boardcomputer, Vivavoce, Autoradio',
        'sicurezza' => 'ABS, Airbag, Airbag testa, Airbag laterali, Airbag Passeggero, Controllo trazione, ESP, Immobilizzatore elettronico, Isofix',
        'immagine' => 'https://img-eu-c1.autohero.com/img/8a08c5f34422d4a58a6395ac7833fd38571f4fae8693a776c21aec37a86a7240/exterior/1/1116x744-0815666282a74823abaa864c6ba1ee80.jpg'
    ],
    [
        'id' => 5,
        'casa_automobilistica' => 'Kia',
        'modello' => "Kia cee'd",
        'prezzo' => 11799,
        'chilometraggio' => 61067,
        'prima_immatricolazione' => '2016 - 06 - 01',
        'CV' => 110,
        'carburante' => 'diesel',
        'classe_del_veicolo' => 'familiare',
        'numero_portiere' => 5,
        'cilindrata' => 1582,
        'paese_origine' => 'germania',
        'targa' => 'FF277FA',
        'numero_proprietari_precedenti' => 1,
        'specifiche_in_evidenza' => null,
        'confort' => 'Alzacristalli elettrici, Bracciolo, Chiusura centralizzata, Climatizzatore, Sensori di parcheggio posteriori, Volante multifunzione, Cruise Control',
        'sistema_multimediale' => 'Autoradio, Bluetooth, Boardcomputer, Vivavoce',
        'sicurezza' => 'ABS, Airbag, Airbag laterali, Airbag passeggeri, Airbag testa, Controllo trazione, ESP, Immobilizzatore elettronico',
        'immagine' => 'https://img-eu-c1.autohero.com/img/1113fc7fe0577024548cbe20a091248c6ad958ad53f6bf3dfb8fa3aaad596125/exterior/1/1116x744-1615639342454759998e5c940e7f6d1f.jpg'
    ],
];
